"""Genera un informe de inconsistencia comparando la resolución (10%) con el análisis pericial (67.4%)"""
from datetime import datetime

def generate_inconsistency_report():
    """Genera un informe detallado de inconsistencia"""
    
    report = []
    report.append("=" * 80)
    report.append("INFORME DE INCONSISTENCIA: RESOLUCIÓN ADMINISTRATIVA vs ANÁLISIS PERICIAL")
    report.append("=" * 80)
    report.append("")
    report.append(f"Fecha de análisis: {datetime.now().strftime('%d/%m/%Y %H:%M')}")
    report.append("")
    
    report.append("1. COMPARACIÓN DE VALORACIONES")
    report.append("-" * 80)
    report.append("")
    report.append("RESOLUCIÓN ADMINISTRATIVA (JCyL):")
    report.append("  - Grado de discapacidad reconocido: 10%")
    report.append("  - Diagnóstico reconocido: Lesión no especificada de hombro (M75.91)")
    report.append("  - Clasificación: Clase 1 (Deficiencia leve: 0-9%)")
    report.append("  - Justificación: Considera solo una lesión genérica sin especificar")
    report.append("")
    report.append("ANÁLISIS PERICIAL (Dr. Alonso - 06/05/2024):")
    report.append("  - Grado de discapacidad estimado: 67.4%")
    report.append("  - BDGP (Anexo III): 60.7%")
    report.append("  - GDA Final: 67.4%")
    report.append("  - Clasificación: Clase 3 (Deficiencia grave: 50-74%)")
    report.append("  - Componentes: 7 deficiencias únicas detectadas")
    report.append("")
    report.append("DIFERENCIA:")
    report.append("  - Diferencia absoluta: 57.4 puntos porcentuales")
    report.append("  - La resolución subestima el grado en un 85%")
    report.append("")
    
    report.append("2. DEFICIENCIAS DETECTADAS EN EL PERICIAL (NO RECONOCIDAS EN LA RESOLUCIÓN)")
    report.append("-" * 80)
    report.append("")
    report.append("Según el análisis del informe pericial, se detectaron las siguientes deficiencias:")
    report.append("")
    report.append("1. Rotura del manguito rotador y Tendinopatía de la Corredera Bicipital - 15%")
    report.append("2. Discinesia escapular (escapulo-humeral) - 15%")
    report.append("3. Amiotrofia Muscular Periescapular y Discinesia Escapular - 20%")
    report.append("4. Lesión tendinosa del manguito rotador - 15%")
    report.append("5. Patología post-quirúrgica (10-02-2023) - 20%")
    report.append("6. Manguito rotador con 3 anclajes óseos - 15%")
    report.append("7. Hombro derecho con incongruencia movilidad activa/pasiva - 15%")
    report.append("")
    report.append("TOTAL (suma directa): 115% → Aplicando fórmula de combinación RD 888/2022: 60.7%")
    report.append("")
    
    report.append("3. ANÁLISIS DE LA JUSTIFICACIÓN DEL 10% EN LA RESOLUCIÓN")
    report.append("-" * 80)
    report.append("")
    report.append("La resolución administrativa asigna un 10% basándose en:")
    report.append("")
    report.append("A. DIAGNÓSTICO GENÉRICO:")
    report.append("   - Utiliza código M75.91: 'Lesión no especificada de hombro'")
    report.append("   - No especifica las múltiples patologías detectadas en el pericial:")
    report.append("     * Rotura del manguito rotador")
    report.append("     * Tendinopatía de la Corredera Bicipital")
    report.append("     * Amiotrofia Muscular Periescapular")
    report.append("     * Discinesia Escapular")
    report.append("     * Secuelas post-quirúrgicas")
    report.append("")
    report.append("B. CLASIFICACIÓN INCORRECTA:")
    report.append("   - Asigna Clase 1 (Deficiencia leve: 0-9%)")
    report.append("   - El 10% estaría en el límite superior de Clase 1")
    report.append("   - Según RD 888/2022, con las limitaciones funcionales detectadas")
    report.append("     (abducción 90º, flexión 100º) debería ser Clase 2 como mínimo")
    report.append("")
    report.append("C. OMISIÓN DE MÚLTIPLES DEFICIENCIAS:")
    report.append("   - Solo reconoce UNA lesión genérica")
    report.append("   - No valora las 7 deficiencias específicas detectadas en el pericial")
    report.append("   - No aplica la fórmula de combinación para múltiples deficiencias")
    report.append("     del mismo sistema (Cap. 15 - Extremidades Superiores)")
    report.append("")
    report.append("D. NO APLICA AJUSTES POR BAREOS SECUNDARIOS:")
    report.append("   - No considera BLA (Limitaciones en Actividad)")
    report.append("   - No considera BRP (Restricciones en Participación)")
    report.append("   - No considera BFCA (Factores Contextuales)")
    report.append("")
    
    report.append("4. FUNDAMENTO LEGAL DEL ERROR")
    report.append("-" * 80)
    report.append("")
    report.append("Según el RD 888/2022:")
    report.append("")
    report.append("Art. 4.2: 'La evaluación de la discapacidad se realizará mediante la aplicación")
    report.append("de los baremos que se acompañan como anexos I, II, III, IV, V y VI.'")
    report.append("")
    report.append("La resolución administrativa INCUMPLE este artículo porque:")
    report.append("")
    report.append("1. No aplica correctamente el Anexo III (BDGP):")
    report.append("   - Debe valorar TODAS las deficiencias detectadas, no solo una genérica")
    report.append("   - Debe aplicar la fórmula de combinación para múltiples deficiencias")
    report.append("   - Debe considerar las limitaciones funcionales específicas (goniometría)")
    report.append("")
    report.append("2. No aplica los Anexos IV, V y VI:")
    report.append("   - Anexo IV (BLA): Limitaciones en actividad laboral y doméstica")
    report.append("   - Anexo V (BRP): Restricciones en participación social y laboral")
    report.append("   - Anexo VI (BFCA): Factores contextuales y barreras ambientales")
    report.append("")
    report.append("3. Utiliza un diagnóstico genérico (M75.91) que no refleja la realidad:")
    report.append("   - El pericial identifica patologías específicas probadas")
    report.append("   - La resolución las ignora y usa un código inespecífico")
    report.append("")
    
    report.append("5. VALORACIÓN TÉCNICA CORRECTA SEGÚN RD 888/2022")
    report.append("-" * 80)
    report.append("")
    report.append("Aplicando correctamente el RD 888/2022:")
    report.append("")
    report.append("BDGP (Anexo III):")
    report.append("  - 7 deficiencias en Cap. 15 (Extremidades Superiores)")
    report.append("  - Aplicando fórmula de combinación: 60.7%")
    report.append("  - Clase 3 (Deficiencia grave: 50-74%)")
    report.append("")
    report.append("BLA (Anexo IV):")
    report.append("  - Limitaciones en movilidad (dominio 4)")
    report.append("  - Limitaciones en vida doméstica (dominio 6)")
    report.append("  - Limitaciones en tareas generales (dominio 2)")
    report.append("  - Estimación: 10-20%")
    report.append("")
    report.append("BRP (Anexo V):")
    report.append("  - Restricciones en participación laboral")
    report.append("  - Necesidad de adaptaciones")
    report.append("  - Estimación: 25-35%")
    report.append("")
    report.append("BFCA (Anexo VI):")
    report.append("  - Factores contextuales: 0-5 puntos")
    report.append("")
    report.append("GDA FINAL (Art. 4.2):")
    report.append("  - BDGP: 60.7%")
    report.append("  - Ajustes: +6.7% (BLA + BRP + BFCA)")
    report.append("  - GDA: 67.4%")
    report.append("  - Clase: 3 (Deficiencia grave)")
    report.append("")
    
    report.append("6. CONCLUSIÓN Y RECOMENDACIONES")
    report.append("-" * 80)
    report.append("")
    report.append("CONCLUSIÓN:")
    report.append("")
    report.append("La valoración del 10% en la resolución administrativa es INCORRECTA y")
    report.append("SUBESTIMADA según el RD 888/2022.")
    report.append("")
    report.append("El análisis técnico demuestra que el grado de discapacidad debería ser")
    report.append("del 67.4%, lo que representa una diferencia de 57.4 puntos porcentuales.")
    report.append("")
    report.append("ERRORES DETECTADOS:")
    report.append("")
    report.append("1. ✓ Diagnóstico genérico (M75.91) que no refleja las patologías específicas")
    report.append("2. ✓ Clasificación incorrecta (Clase 1 en lugar de Clase 3)")
    report.append("3. ✓ Omisión de 6 deficiencias adicionales detectadas en el pericial")
    report.append("4. ✓ No aplicación de la fórmula de combinación para múltiples deficiencias")
    report.append("5. ✓ No consideración de los baremos secundarios (BLA, BRP, BFCA)")
    report.append("6. ✓ No valoración de limitaciones funcionales específicas (goniometría)")
    report.append("")
    report.append("RECOMENDACIONES:")
    report.append("")
    report.append("1. RECLAMACIÓN ADMINISTRATIVA:")
    report.append("   - Presentar reclamación previa solicitando revisión de la valoración")
    report.append("   - Anexar este informe técnico como fundamento")
    report.append("   - Solicitar reconocimiento del 67.4% según RD 888/2022")
    report.append("")
    report.append("2. FUNDAMENTOS LEGALES:")
    report.append("   - Art. 4.2 RD 888/2022: Aplicación correcta de todos los baremos")
    report.append("   - Anexo III: Valoración de TODAS las deficiencias detectadas")
    report.append("   - Anexo I: Metodología de combinación de deficiencias")
    report.append("   - Art. 2.2 RD 888/2022: Criterios técnicos unificados")
    report.append("")
    report.append("3. IMPLICACIONES JURÍDICAS:")
    report.append("   - El 67.4% supera el mínimo del 33% para reconocimiento de discapacidad")
    report.append("   - Justifica Incapacidad Permanente Parcial para la profesión habitual")
    report.append("   - Da base técnica sólida para la reclamación")
    report.append("")
    report.append("=" * 80)
    report.append("Fin del informe de inconsistencia")
    report.append("=" * 80)
    
    return "\n".join(report)

if __name__ == "__main__":
    report = generate_inconsistency_report()
    print(report)
    
    # Guardar en archivo
    with open("informe_inconsistencia.txt", "w", encoding="utf-8") as f:
        f.write(report)
    print("\n\nInforme guardado en: informe_inconsistencia.txt")




